### ISSUE TITLE
Beken Bk7252 application software setup Wi-Fi tests 

### ISSUE THREAD

**Issue by Ducomex** [illusionlee/lightcube#3]
Hi dears.

I'm looking for an app at beken, to be able make Wi-Fi continuous test by RF cable.

It's necessary to get a certified from Brazil government (Anatel) they require wifi test to all products.

The chipset of beken Bk7252 is in a mini camera wifi.

Tks

![Screenshot_20220104-223224](https://user-images.githubusercontent.com/97136892/148146863-30f832fc-c8ca-4322-b896-459dd0ff82f5.png)

![Screenshot_20220104-223240](https://user-images.githubusercontent.com/97136892/148146876-e34ae9e5-0267-4aa8-92e7-19968589be8e.png)

![Screenshot_20220104-223309](https://user-images.githubusercontent.com/97136892/148146896-7c685746-0006-4ab9-98e3-f00c4392e19b.png)

**Comment by illusionlee** [comment]
sorry, i can't do anything for u.

**Comment by Bluscream** [comment]
Why?
